name: Create Release Assets

on:
  push:
    tags: ['v*']
jobs:
  release-asset-linux:
    name: Linux Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Build on Linux
        id: build-linux
        run: cargo build --release
      - name: Upload Linux Asset Artifact
        id: upload-linux
        uses: actions/upload-artifact@v2.1.3
        with:
          name: favlist-ubuntu-latest
          path: target/release/favlist
  release-asset-windows:
    name: Windows Release Asset
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Build on Windows
        id: build-windows
        run: cargo build --release
      - name: Upload Windows Asset
        id: upload-windows
        uses: actions/upload-artifact@v2.1.3
        with:
          name: favlist-windows-latest.exe
          path: target/release/favlist.exe
