name: Create Release

on:
  push:
    tags: ['v*']
jobs:
  make-release:
    name: Make Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
  release-asset-linux:
    name: Linux Release Asset
    runs-on: ubuntu-latest
    needs: [make-release]
    steps:
      - name: Build on Linux
        id: build-linux
        run: cargo build --release
      - name: Upload Linux Asset Artifact
        id: upload-linux
        uses: actions/upload-artifact@v1
        with:
          name: favlist-ubuntu-latest
          path: target/release/favlist
  release-asset-windows:
    name: Windows Release Asset
    runs-on: windows-latest
    needs: [make-release]
    steps:
      - name: Build on Windows
        id: build-windows
        run: cargo build --release
      - name: Upload Windows Asset
        id: upload-windows
        uses: actions/upload-artifact@v1
        with:
          name: favlist-windows-latest.exe
          path: target/release/favlist.exe
